name: 05-1-filters-activity-types

on: 
    pull_request:
        types: [opened , synchronize]
        branches: [main]

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Runnning Wherever a PR is opened or Synchronized asn base branch is main"
