name: 08 - Using Variable

on: 
    push:
    workflow_dispatch:

env:
    WORKFLOW_VAR: 'I am Workflow'

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: 'I am job env var'
        steps:
            - name: Print ENV variable
              env:
                STEP_VAR: 'I am a step env var'
                step_var2: 'I am a another step env var'
              run: |
               echo "Step env var: ${{env.STEP_VAR}}"
               echo "Step env var 2: $step_var2"
               echo "Job env var: ${{env.JOB_VAR}}"
               echo "Job env var: ${{env.WORKFLOW_VAR}}"
