name: 17 - Custom Actins - Composite

on:
    workflow_dispatch:
    
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        steps:
            - name: Checkoout code
              uses: actions/checkout@v4
            - name: Setup Node and NPM Dependencies
              uses: ./.github/actions/composite-cache-deps
              with:
                node-version: 24.x
            - name: Install Dependencies
              run: npm ci
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
