name: 14 - working with artifacts

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        steps:
            - name: Checkoout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Download cached dependencies
              uses: actions/cache@v3
              id: cache
              with:
                path: 04-using-actions/react-app/node_modules
                key: deps-node-modules-${{hashFiles('04-using-actions/react-app/package-lock.json')}}
            - name: Install Dependencies
              if: ${{steps.cache.outputs.cache-hit !='true'}}
              run: npm ci
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build